name: YAML Helper
description: Simple yaml helper that allows merging values into existing yaml files
author: Liam Johnston

branding:
  icon: file-text
  color: red

inputs:
  file-location:
    description: Location of the yaml file
    required: true
  create-if-does-not-exist:
    description: Should the file be created if it doesn't exist
    required: false
    default: "true"
  content:
    required: false
    description: The contents of the file in YAML format
    default: ""
  yaml-schema:
    required: false
    description: Schema for the yaml file if using a yaml-file-server
    default: ""

outputs:
  file-location:
    description: Where the outputted file was written to
  file-created:
    description: If a new file was created from this action
  file-contents:
    description: The final contents of the resultant file

runs:
  using: node20
  main: index.js
