name: The name of your action here
description: Provide a description here
author: Liam Johnston

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

inputs:
  file-location:
    description: Location of the yaml file
    required: true
  create-if-does-not-exist:
    description: Should the file be created if it doesn't exist
    required: false
    default: 'false'
  content:
    required: true
    description: The contents of the file in YAML format
  yaml-schema:
    required: false
    description: Schema for the yaml file if using a yaml-file-server

# TODO: Provide Useful Outputs
# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
