name: Push to Main

on:
  push:
   branches:
     - main

permissions:
  contents: write

jobs:
  bump-version:
   name: Bump Action Version
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Git config
      run: |
        git config user.name actions-bot
        git config user.email actions-bot@users.noreply.github.com

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install & Build
      run: |
        bun install --frozen-lockfile --production
        bun build src/index.ts --outdir=dist --target=node

    - name: Bump Version
      run: |
        bunx commit-and-tag-version@12.4.1
        git push --follow-tags origin main
        echo "TAG_VERSION=$(git tag --points-at HEAD)" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          action.yaml
          dist/*
        tag_name: ${{ env.TAG_VERSION }}
